id: BCSeditor
name: BCSL Editor
description: This is a tour created to describe BCSL interactive editor.
title_default: Galaxy Tour
steps:
  - title: Step 1 - Open editor
    element: '#dropdown-button-visualization'
    content: "Select Visualise in <br>the navigation bar."
    placement: right
  - title: Step 2 - Open editor
    element: 'a[href$="/galaxy/visualizations"]'
    content: "Select: Create Visualization."
    placement: left
  - title: Step 3 - Open editor
    element: '#center > div > div > div > div > div:nth-child(3) > table'
    content: "Choose BCSL Editor among <br>the visualisation tools."
    placement: bottom
  - title: Step 4 - BCS file
    element: >-
      #center .center-container .center-panel .ui-thumbnails table tr td
      .ui-select .select
    content: "Select one of stored <br>.bcs files from history."
    placement: left
  - title: Step 5 - Start editor
    element: >-
      #center > div > div > div > div > div:nth-child(3) > table >
      tr:nth-child(2) > td:nth-child(2) > div > button
    content: "Click Create Visualisation."
    placement: right
  - title: Step 7 - Editor workspace
    element: 'div[tour_id="editor"]'
    content: "Here is a workspace for your BCSL model."
    placement: right
  - title: Step 8 - Cursor Position
    element: 'div#actualPosition'
    content: "Position of the <br>cursor in the file."
    placement: bottom
  - title: Step 9 - Undo
    element: 'input#undo_btn.button'
    content: "You can undo your changes."
    placement: bottom
  - title: Step 10 - Redo
    element: 'input#redo_btn.button'
    content: "As well as redo."
    placement: bottom
  - title: Step 11 - Save model
    element: 'input#save_btn.button'
    content:
      "Finally, click Save modifications button <br>
      to create a new BCSL model file in your history."
    placement: bottom
  - title: Step 12 - Results
    element: .list-items
    content:
      "Wait while your modified <br>
      BCSL model is stored in the History."
    placement: left
