id: ProbabilitySampling
name: Probability Sampling
description: This is a tour created to describe Probability Sampling tool.
title_default: Galaxy Tour
steps:
  - title: Step 1 - Begin
    element: >-
      #left .unified-panel .unified-panel-body .toolMenuContainer .toolMenu
      .toolSectionTitle.tool-menu-section-default a[href$="javascript:void(0)"]
      .name
    content: Click here to list available tools.
    placement: bottom
  - title: Step 2 - Select tool
    element: >-
      #left > div.unified-panel > div.unified-panel-body > div > div.toolMenu >
      div:nth-child(4) > div > div > div:nth-child(2) > div:nth-child(6) > a
    content: "Click on Probability Sampling tool."
    placement: bottom
  - title: Step 3 - Storm output file
    element: 'div[tour_id="storm_file"]'
    content: >-
      "Choose appropriate results of Parameter Synthesis."
    placement: auto
  - title: Step 4 - Parameter name
    element: 'div[tour_id="regions_0|param"]'
    content: "Enter parameter name."
    placement: bottom
  - title: Step 5 - Parameter interval start
    element: 'div[tour_id="regions_0|from"]'
    content: "Enter start of the interval."
    placement: bottom
  - title: Step 6 - Parameter interval end
    element: 'div[tour_id="regions_0|to"]'
    content: "Enter end of the interval."
    placement: bottom
  - title: Step 7 - Parameter number of samples
    element: 'div[tour_id="regions_0|number"]'
    content: "Specify number of samples for this parameter."
    placement: bottom
  - title: Step 8 - Insert interval
    element: '#center .ui-button-default.btn.btn-secondary.float-none.form-repeat-add'
    content: Insert values for another parameter.<br>
    Please specify values for all unknown parameters."
    placement: right
  - title: Step 9 - Delete interval
    element: '#button_delete'
    content: "Option to delete a parameter."
    placement: left
  - title: Step 10 - Execute
    element: '#execute'
    content: "Click the button Execute <br>to start parameter sampling."
    placement: auto
  - title: Step 11 - Results
    element: .list-items
    content: >-
      "Wait until the parameter sampling is <br>
       finished and results stored in the History."
    placement: left