id: SA-ContextBasedReduction
name: Static Analysis - Context based reduction
description: >-
  This is a tour created to describe Static Analysis tool - Context based
  reduction
title_default: Static Analysis - Context based reduction
steps:
  - title: Step 1 - Begin
    element: >-
      #left .unified-panel .unified-panel-body .toolMenuContainer .toolMenu
      .toolSectionTitle.tool-menu-section-default a[href$="javascript:void(0)"]
      .name
    content: Click here to list available tools.
    placement: bottom
  - title: Step 2 - Select tool
    element: >-
      #left > div.unified-panel > div.unified-panel-body > div > div.toolMenu >
      div:nth-child(4) > div > div > div:nth-child(2) > div:nth-child(5) > a
    content: "Click on Static Analysis tool."
    placement: bottom
  - title: Step 3 - Model file
    element: 'div[tour_id="model"]'
    content:
      "Choose BCSL model file. <br>
      This tool supports only .bcs files stored in your history."
    placement: auto
  - title: Step 4 - Choose method
    element: '#center .center-container .center-panel .ui-portlet .portlet-content .portlet-body .ui-form-element .ui-form-field .ui-select .select2-container'
    content: "Select Context based reduction method."
    placement: bottom
  - title: Step 5 - Execute
    element: '#execute'
    content: "Click the button Execute <br>to start the analysis."
    placement: auto
  - title: Step 6 - Results
    element: .list-items
    content:
      "Wait until the analysis is finished<br>
       and results stored in the History."
    placement: left