id: Simulation-Deterministic
name: Simulation - Deterministic
description: This is a tour created to describe deterministic simulation.
title_default: Simulation - Deterministic
steps:
  - title: Step 1 - Begin
    element: >-
      #left .unified-panel .unified-panel-body .toolMenuContainer .toolMenu
      .toolSectionTitle.tool-menu-section-default a[href$="javascript:void(0)"]
      .name
    content: Click here to list available tools.
    placement: bottom
  - title: Step 2 - Select tool
    element: >-
      #left > div.unified-panel > div.unified-panel-body > div > div.toolMenu >
      div:nth-child(4) > div > div > div:nth-child(2) > div:nth-child(2) > a >
      span.name.font-weight-bold
    content: "Click on Simulation tool."
    placement: bottom
  - title: Step 3 - Model file
    element: 'div[tour_id="model"]'
    content:
      "Choose BCSL model file. <br>
      This tool supports only .bcs files stored in your history."
    placement: bottom
  - title: Step 4 - Simulation method
    element: '#center .center-container .center-panel .ui-portlet .portlet-content .portlet-body .ui-form-element .ui-form-field .ui-select .select2-container'
    content: "Select Deterministic method."
    placement: bottom
  - title: Step 5 - Volume
    element: 'div[tour_id="type|volume"]'
    content: "Specify volume of the system in liters."
    placement: bottom
  - title: Step 6 - Simulation step
    element: 'div[tour_id="type|step"]'
    content: "Specify fineness of simulation steps."
    placement: bottom
  - title: Step 7 - Simulation time
    element: 'div[tour_id="max_time"]'
    content: "Specify simulation duration."
    placement: bottom
  - title: Step 8 - Execute
    element: '#execute'
    content: "Click the button Execute <br>to start the simulation."
    placement: auto
  - title: Step 9 - Results
    element: .list-items
    content:
      "Wait until the simulation is finished<br>
       and results stored in the History."
    placement: left