id: TransitionSystemGenerator
name: Transition System generator
description: This is a tour created to describe Transition System generator tool.
title_default: Transition System generator tour
steps:
  - title: Step 1 - Begin
    element: >-
      #left .unified-panel .unified-panel-body .toolMenuContainer .toolMenu
      .toolSectionTitle.tool-menu-section-default a[href$="javascript:void(0)"]
      .name
    content: Click here to list available tools.
    placement: bottom
  - title: Step 2 - Select tool
    element: >-
      #left > div.unified-panel > div.unified-panel-body > div > div.toolMenu >
      div:nth-child(4) > div > div > div:nth-child(2) > div:nth-child(1) > a
    content: "Click on Transition System generator tool."
    placement: bottom
  - title: Step 3 - Model file
    element: 'div[tour_id="model"]'
    content: >-
      "Choose BCSL model file. <br>
      This tool supports only .bcs files stored in your history."
    placement: auto
  - title: Step 4 - Bound
    element: 'div[tour_id="bound"]'
    content: "Specify agents boundary cap (optional)."
    placement: auto
  - title: Step 5 - Advanced options
    element: '#center .portlet-header'
    content: "You can expand Advanced Options to edit more attributes."
    placement: bottom
  - title: Step 5.1 - Advanced options - Maximal computational time
    element: 'div[tour_id="adv|max_time"]'
    content: "Select maximal allowed computational time (in seconds)."
    placement: bottom
  - title: Step 5.2 - Advanced options - Maximal TS size
    element: 'div[tour_id="adv|max_size"]'
    content: "Select maximal allowed size of resulting Transition System."
    placement: bottom
  - title: Step 5.3 - Advanced options - Precomputed TS file
    element: 'div[tour_id="adv|transition_file"]'
    content: "You can choose a precomputed Transition System file."
    placement: bottom
  - title: Step 6 - Execute
    element: '#execute'
    content: "Click the button Execute <br>to start generating Transition System."
    placement: auto
  - title: Step 7 - Results
    element: .list-items
    content: >-
      "Wait until the Transition System generating is <br>
       finished and results stored in the History."
    placement: left